version: "3.8"

services:
    redis:
      image: redis:latest
      container_name: redis_server
      ports:
        - 6379:6379
      restart: unless-stopped
      volumes:
        - pre_onboarding-redis:/data

    worker:
      build:
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      command: celery -A pre_onboarding worker --loglevel=info
      depends_on:
        - redis
      volumes:
        - ./:/app/

volumes:
  pre_onboarding:
  pre_onboarding-data:
  pre_onboarding-redis: