version: "3.8"

services:
    redis:
      image: redis:latest
      container_name: redis_server
      ports:
        - "6379:6379"
      restart: unless-stopped
      volumes:
        - pre_onboarding-redis:/data

    django:
      container_name: django_service
      image: django
      build: .
      command: python3 manage.py runserver 0.0.0.0:8080
      volumes:
        - .:/django
      ports:
        - "8080:8080"
      depends_on:
        - redis

    celery:
      build:
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      command: celery -A pre_onboarding worker --loglevel=info
      depends_on:
        - redis
      volumes:
        - ./:/app/

volumes:
  pre_onboarding:
  pre_onboarding-redis: